In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#geberatic systhetic data points

np.random.seed(1)

In [ ]:
#generating symnthetic X

X = 2 * np.random.rand(100,1)

In [ ]:
X

array([[0.6532898 ],
       [1.0541162 ],
       [1.7718842 ],
       [0.71453952],
       [1.8170703 ],
       [1.24672023],
       [0.03164249],
       [1.85887447],
       [1.38179384],
       [1.9946457 ],
       [0.34468102],
       [0.2742715 ],
       [1.86519093],
       [1.39363632],
       [0.13200035],
       [1.51092611],
       [1.50775238],
       [1.84604907],
       [1.42304952],
       [0.24854192],
       [0.03976027],
       [0.05242197],
       [0.05661298],
       [0.49242214],
       [1.7200559 ],
       [1.07766213],
       [1.10564396],
       [1.68406178],
       [0.24834663],
       [0.55836736],
       [1.17151854],
       [1.9391915 ],
       [1.12206044],
       [0.03729458],
       [1.60126535],
       [0.46594855],
       [1.61421039],
       [0.77572129],
       [1.72708371],
       [1.49424329],
       [1.11248047],
       [0.27291045],
       [0.11983538],
       [0.24268691],
       [0.08910376],
       [0.21498826],
       [0.45141868],
       [1.425

In [ ]:
#generating synthetic data points y

y = 4 + 3*1.5*X**2+ np.random.randn(100,1)

In [ ]:
y

array([[ 6.16321349],
       [ 9.20205456],
       [18.78910155],
       [ 8.08970847],
       [18.7373856 ],
       [ 9.76128028],
       [ 2.82218748],
       [18.88360977],
       [10.9178981 ],
       [22.72878145],
       [ 4.03640895],
       [ 4.02752687],
       [19.65332588],
       [11.34337948],
       [ 3.21709205],
       [14.94775115],
       [14.84846667],
       [18.89236535],
       [14.92334959],
       [ 2.97225197],
       [ 3.66212674],
       [ 3.78152654],
       [ 1.22133763],
       [ 7.02868683],
       [17.67999732],
       [ 8.1815111 ],
       [11.55219196],
       [17.34795043],
       [ 4.70706836],
       [ 4.79598508],
       [10.28227336],
       [19.39640616],
       [10.46061442],
       [ 3.63182067],
       [15.67227637],
       [ 6.17904108],
       [16.01028645],
       [ 6.97031327],
       [17.69918093],
       [13.31416188],
       [10.40526228],
       [ 5.87851963],
       [ 4.82342799],
       [ 5.14994503],
       [ 3.15844614],
       [ 3

In [ ]:
#train_test_split

from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2, random_state = 1)

In [ ]:
X_train.shape , X_test.shape

((80, 1), (20, 1))

In [ ]:
#perform polynomial regression

from sklearn.preprocessing import PolynomialFeatures

In [ ]:
degree = 2
poly_features = PolynomialFeatures(degree = 2, include_bias = False)
X_poly_train = poly_features.fit_transform(X_train)

In [ ]:
X_poly_train

array([[1.77188420e+00, 3.13957361e+00],
       [7.60282345e-01, 5.78029244e-01],
       [4.68724172e-01, 2.19702350e-01],
       [1.23991144e+00, 1.53738037e+00],
       [2.48541924e-01, 6.17730880e-02],
       [4.65948548e-01, 2.17108049e-01],
       [1.81563171e+00, 3.29651849e+00],
       [1.68406178e+00, 2.83606409e+00],
       [4.51418677e-01, 2.03778822e-01],
       [1.72708371e+00, 2.98281814e+00],
       [9.72690222e-01, 9.46126268e-01],
       [1.89803264e+00, 3.60252791e+00],
       [5.04651489e-01, 2.54673125e-01],
       [1.86394414e+00, 3.47428775e+00],
       [1.04934062e+00, 1.10111573e+00],
       [1.11248047e+00, 1.23761279e+00],
       [1.11943396e+00, 1.25313240e+00],
       [1.69365760e+00, 2.86847608e+00],
       [4.92422135e-01, 2.42479559e-01],
       [1.60126535e+00, 2.56405071e+00],
       [3.86868565e-01, 1.49667287e-01],
       [4.06586469e-01, 1.65312557e-01],
       [5.29839115e-01, 2.80729488e-01],
       [1.51092611e+00, 2.28289770e+00],
       [1.330729

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
poly_reg = LinearRegression()

In [ ]:
poly_reg

LinearRegression()

In [ ]:
poly_reg.fit(X_poly_train , y_train)

LinearRegression()